### PR TITLE
Feature/ot162 58

### PR DESCRIPTION
**Pull request by mikesanmartin**
Issue OT162-58 https://alkemy-labs.atlassian.net/browse/OT162-58

Creation of component that recieve a HTML String and render it as HTML code.
image
Showing an expample on console:
image

In case of not having information to display, it will be a message for the user.
image

### CODE REVIEW

**Comment by GauntStrelok** [comment]
> Issue OT162-58 [https://alkemy-labs.atlassian.net/jira/software/c/projects/OT162/boards/235?modal=detail&selectedIssue=OT162-58&assignee=6230a40433fb8400696624dc](url)

Esta mal el link al issue, cuidado con eso, si necesitas, te muestro la forma de copiarlo correctamente

**Comment by GauntStrelok** [comment]
Hacer pull de main para arreglar conflictos

**Comment by GauntStrelok** [comment]
Falta ademas cargar las horas en JIRA

**Comment by mikesanmartin** [comment]
> > Issue OT162-58 [https://alkemy-labs.atlassian.net/jira/software/c/projects/OT162/boards/235?modal=detail&selectedIssue=OT162-58&assignee=6230a40433fb8400696624dc](url)
> 
> Esta mal el link al issue, cuidado con eso, si necesitas, te muestro la forma de copiarlo correctamente

Edited and solved.

**Comment by mikesanmartin** [comment]
> Hacer pull de main para arreglar conflictos

Fix done.

**Comment by mikesanmartin** [comment]
> Falta ademas cargar las horas en JIRA

updated.

**Pull request merged**
